entity_prefix = 'urn:rescuecore2.standard:entity:'
property_prefix = 'urn:rescuecore2.standard:property:'
message_prefix = 'urn:rescuecore2.standard:message:'

fire_brigade_urn = entity_prefix + 'firebrigade'
police_force_urn = entity_prefix + 'policeforce'
ambulance_team_urn = entity_prefix + 'ambulanceteam'

x_urn = property_prefix + 'x'
y_urn = property_prefix + 'y'

edges_urn = property_prefix + 'edges'
blockades_urn = property_prefix + 'blockades'

start_time_urn = property_prefix + 'starttime'
longitude_urn = property_prefix + 'longitude'
latitude_urn = property_prefix + 'latitude'
wind_force_urn = property_prefix + 'windforce'
wind_direction_urn = property_prefix + 'winddirection'

floors_urn = property_prefix + 'floors'
ignition_urn = property_prefix + 'ignition'
fieryness_urn = property_prefix + 'fieryness'
brokenness_urn = property_prefix + 'brokenness'
building_code_urn = property_prefix + 'buildingcode'
attributes_urn = property_prefix + 'attributes'
ground_area_urn = property_prefix + 'buildinggroundarea'
area_total_urn = property_prefix + 'buildingareatotal'
temperature_urn = property_prefix + 'temperature'
importance_urn = property_prefix + 'importance'
position_urn = property_prefix + 'position'
apexes_urn = property_prefix + 'apexes'
repair_cost_urn = property_prefix + 'repaircost'
travel_distance_urn = property_prefix + 'traveldistance'
water_urn = property_prefix + 'waterquantity'
position_history_urn = property_prefix + 'positionhistory'
direction_urn = property_prefix + 'direction'
stamina_urn = property_prefix + 'stamina'
hp_urn = property_prefix + 'hp'
damage_urn = property_prefix + 'damage'
buriedness_urn = property_prefix + 'buriedness'

